server:
  port: 8080


spring:
  data:
    solr:
      host: http://localhost:8983/solr/yida
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: xmu.yida.solrlearn.domain.po
  configuration:
    map-underscore-to-camel-case: true